HEADS AAA

START *** PLACE *** SDD
PLACE *** PLACE1 *** SSD

PLACE1 *** DANCEUP +.. RRR

DANCEUP +.. DANCEUP *** RRR
DANCEUP .@. DANCEUP +** RRR
DANCEUP ... DANCEDOWN +++ RRR
DANCEUP ___ STOP *** SSS

DANCEDOWN .@. DANCEDOWN .@+ RRR
DANCEDOWN ... DANCEUP +++ RRR
DANCEDOWN ___ TURNDOWN *** LLL

TURNDOWN +++ TURNDOWN1 *** LLS
TURNDOWN1 +@+ TURNDOWN1 *** DDS
TURNDOWN1 @.+ TURNDOWN1 *** DSS
TURNDOWN1 ..+ DANCELEFT ++* LSS
TURNDOWN1 +++ DANCELEFT *** DDD

DANCELEFT +++ DANCELEFT *** DDD
DANCELEFT .++ DANCELEFT +** DDD
DANCELEFT .@. DANCELEFT +** DDD
DANCELEFT ... DANCERIGHT +++ DDD
DANCELEFT ___ STOP *** SSS

DANCERIGHT .@. DANCERIGHT .*+ DDD
DANCERIGHT ... DANCELEFT +++ SSS
DANCERIGHT ___ STOP *** SSS