HEADS AAD

START *** PLACE *** SDS
PLACE *** DANCEUP +.. RRR

DANCEUP +.. DANCEUP *** RRR
DANCEUP .@. DANCEUP +** RRR
DANCEUP ... DANCEDOWN +++ RRR
DANCEUP ___ STOP *** SSS

DANCEDOWN .@. DANCEDOWN .@+ RRR
DANCEDOWN ... DANCEUP +++ RRR
DANCEDOWN ___ STOP *** SSS