HEADS AAA

START *** PLACE *** SDD
PLACE *** DANCEDOWN *** SSD

DANCEUP +.. DANCEUP *** RRR
DANCEUP .@. DANCEUP +** RRR
DANCEUP ... DANCEDOWN +++ RRR
DANCEUP ___ STOP *** SSS

DANCEDOWN .@. DANCEDOWN .@+ RRR
DANCEDOWN ... DANCEUP +++ RRR
DANCEDOWN ___ TURNDOWN *** LLL

TURNDOWN +++ TURNDOWN1 *** DLL
TURNDOWN1 +@. TURNDOWN2 *** DDL
TURNDOWN2 +.+ DANCELEFT *+* DDD
TURNDOWN2 +.. DANCELEFT *++ DDD

DANCELEFT +.. DANCELEFT *++ DDD
DANCELEFT +++ DANCELEFT *** DDD
DANCELEFT .++ DANCELEFT **+ DDD
DANCELEFT .@. DANCELEFT **+ DDD
DANCELEFT ... DANCERIGHT +++ DDD
DANCELEFT ___ TURNLEFT *** UUU

DANCERIGHT .@. DANCERIGHT +** DDD
DANCERIGHT .@@ TURNLEFT *** DRR
DANCERIGHT @@. TURNLEFT **+ USD
DANCERIGHT ... DANCELEFT +++ SSS
DANCERIGHT ___ STOP *** SSS

TURNLEFT +++ TURNLEFT *** LSU
TURNLEFT ++. TURNLEFT *** LUU
TURNLEFT +@. TURNLEFT *** LUU
TURNLEFT +@+ TURNLEFT *** SLS
TURNLEFT +.+ DANCETOP *+* SSS
TURNLEFT *@@ TURNLEFT *** SRR
TURNLEFT ..@ TURNLEFT *** SSR
TURNLEFT ... DANCEBOTTOM *** SSU

DANCEBOTTOM ..+ DANCEBOTTOM ++* LLL
DANCEBOTTOM .@+ DANCEBOTTOM +** LLL
DANCEBOTTOM .@. DANCEBOTTOM +** LLL
DANCEBOTTOM ... DANCETOP +++ LLL

DANCETOP +++ DANCETOP *** LLL
DANCETOP .@. DANCETOP **+ LLL
DANCETOP ... DANCEBOTTOM +++ LLL
DANCETOP ___ TURNUP *** RRR

TURNUP ___ TURNUP *** URR
TURNUP _++ TURNUP *** URR
TURNUP +++ TURNUP *** USR
TURNUP ++. TURNUP *** URR
TURNUP +@+ DANCEUPR *** SUS
TURNUP +@. TURNUP *** SUS
TURNUP +.. DANCEUPR *++ UUU

DANCEUPR +.+ DANCEUPR *+* UUU
DANCEUPR .@. DANCEUPR **+ UUU
DANCEUPR ... DANCEUPL +++ UUU
DANCEUPR ..+ DANCEUPL ++* UUU
DANCEUPR +.. DANCEUPL *++ UUU
DANCEUPR +@+ STOP *** SSS

DANCEUPL .@+ STOP +** SSS
DANCEUPL .@. DANCEUPL +** UUU
DANCEUPL ... DANCEUPR +++ UUU
DANCEUPL .@@ STOP +** SSS
DANCEUPL +@@ STOP *** SSS