HEADS AAAA

START #### LOCATE **** SRSR
LOCATE #=#= LOOP **** SSDD
LOCATE #|#| LOOP **** SSDD
LOCATE #=__ STOP **** SSSS

LOOP #=#| CLEANUP #|** RRRR
LOOP #|#= CLEANDOWN ***| RRRR
LOOP #=#= LOOP **** RRRR
LOOP #|#| LOOP **** DDDD
LOOP ==== LOOP **** RRRR
LOOP ===| LOOP **** RRRR
LOOP =|== LOOP **** RRRR
LOOP =|=| NEXTLINE **** LLLL
LOOP =!|_ CLEANUP |_** RRRR
LOOP |_=! CLEANDOWN **|_ RRRR

LOOP !!__ STOP **** SSSS

CLEANUP |=** CLEANUP *_** RRRR
CLEANUP _=** CLEANUP *_** RRRR
CLEANUP _|** BACKTRACK *_** LLLL
CLEANUP ||** CLEANUP *_** RRRR
CLEANUP !_!_ BACKTRACK **** LLLL
CLEANUP ____ BACKTRACK **** LLLL

CLEANDOWN **|= CLEANDOWN ***_ RRRR
CLEANDOWN **_= CLEANDOWN ***_ RRRR
CLEANDOWN **_| BACKTRACK ***_ LLLL
CLEANDOWN **|| CLEANDOWN ***_ RRRR
CLEANDOWN !_!_ BACKTRACK **** LLLL
CLEANDOWN ____ BACKTRACK **** LLLL

GOINIT ==== GOINIT **** UUUU
GOINIT #|#| LOOP **** DDDD
GOINIT __!! LOOP **** DDDD

NEXTLINE !!!! NEXTLINE **** LLLL
NEXTLINE _!_! STEPDOWN **** DDDD
STEPDOWN **** LOOP **** RRRR 

BACKTRACK !!!! BACKTRACK **** LLLL
BACKTRACK !_!_ BACKTRACK **** LLLL
BACKTRACK ____ BACKTRACK ____ LLLL
BACKTRACK _!_! GOSTART **** UUUU

GOSTART _!_! GOSTART **** UUUU
GOSTART ___! GOSTART **** RRRR
GOSTART __!! LOOP **** DDDD
GODOWN _!_! LOOP **** RRRR
GODOWN **__ STOP **** SSSS
