HEADS AAAA

START **** LOCATE0 **** RRRR
LOCATE0 **** LOCATE1 **** SRRR
LOCATE1 **** LOCATE2 **** SSRR
LOCATE2 **** SEARCH1 **** SSSR

SEARCH1 |___ UP2 **** SSSS
SEARCH1 !!__ SEARCH1 **** DDDD
SEARCH1 !!!_ SEARCH1 **** DDDD
SEARCH1 !!!! SEARCH1 **** DDDD
SEARCH1 ____ UP1 **** UUUU
UP1 !*** UP1 **** UUUU
UP1 ____ MOVER1 **** RRRR
MOVER1 ____ SEARCH1 **** DDDD

UP2 !*** UP2 **** UUUU
UP2 ____ MOVER2 **** RRRR
MOVER2 ____ SEARCH2 **** DDDD

SEARCH2 |___ PUTEND **** SSSS
SEARCH2 !!__ SEARCH2 **** DDDD
SEARCH2 !!!_ SEARCH2 **** DDDD
SEARCH2 !!!! SEARCH2 **** DDDD
SEARCH2 ____ SCANDOWN ____ DDDD
SCANDOWN !*** SCANDOWN **** DDDD
SCANDOWN ____ CHECKBOTTOM **** SSSS
CHECKBOTTOM ____ PUTEND **** UUUU
CHECKBOTTOM !*** SCANDOWN **** DDDD

PUTEND !*** PUTEND **** UUUU
PUTEND ____ MOVEEND **** DDDD
MOVEEND !*** MOVEEND |___ DDDD
MOVEEND ____ DOWNEND ____ SSSS

DOWNEND ____ STOP ____ SSSS
