HEADS AAAA

START **** CONSUME **** LSRD

CONSUME *#** CONSUME *#** RRRR
CONSUME #=#* CONSUME #~** RRRR
CONSUME #==* CONSUME #~** RRRR
CONSUME ~==* CONSUME *~*~ RRRR
CONSUME ~=#* CONSUME *~** RRRR
CONSUME *_** STOP **** SSSS