HEADS AAA

START ### START *** RRR
START === START ~~~ RRR
START ___ GOLEFT *** LLL
GOLEFT !!! GOLEFT *** LLL
GOLEFT ___ S1 *** RRR
S1 *** S2 *** SRR
S2 *** PROCESS *** SSR

PROCESS ~~~ E1 *** DDD
PROCESS #!! PROCESS *** RRR
PROCESS ~#! PROCESS *** RRR
PROCESS ~~# PROCESS *** RRR
PROCESS !!_ STOP *** SSS
PROCESS !__ STOP *** SSS

E1 *** EXCAVATE *** LLL
EXCAVATE _** GOUP **~ UUU
EXCAVATE ~_* GOUP **~ UUU
EXCAVATE ~~_ E1 **~ DDD

GOUP ___ GODOWN *** RRR
GODOWN *** PROCESS *** DDD
GOUP __! GORIGHT *** UUU
GOUP _!* GORIGHT *** UUU
GOUP !** GORIGHT *** UUU
GORIGHT *** GOUP *** RRR