HEADS AAB

START *** INIT *** SDR

INIT AA* ADDONE __P SSR
INIT AB* ADDTWO __P SSR
INIT AC* ADDFOUR __P SSR
INIT AD* ADDSIX __P SSR
INIT A_* INIT __* RRS
INIT BA* ADDTWO __P SSR
INIT BB* ADDTHREE __P SSR
INIT BC* ADDFIVE __P SSR
INIT BD* ADDSEVEN __P SSR
INIT B_* INIT __P RRR
INIT CA* ADDFOUR __P SSR
INIT CB* ADDFIVE __P SSR
INIT CC* ADDSEVEN __P SSR
INIT CD* ADDNINE __P SSR
INIT C_* ADDTWO __P SSR
INIT DA* ADDSIX __P SSR
INIT DB* ADDSEVEN __P SSR
INIT DC* ADDNINE __P SSR
INIT DD* ADDELEVEN __P SSR
INIT D_* ADDFOUR __P SSR

INIT ___ STOP ___ SSS
INIT P__ STOP *** SSS

ADDTWELVE __* ADDELEVEN __P SSR
ADDELEVEN __* ADDTEN __P SSR
ADDTEN __* ADDNINE __P SSR
ADDNINE __* ADDEIGHT __P SSR
ADDEIGHT __* ADDSEVEN __P SSR
ADDSEVEN __* ADDSIX __P SSR
ADDSIX __* ADDFIVE __P SSR
ADDFIVE __* ADDFOUR __P SSR
ADDFOUR __* ADDTHREE __P SSR
ADDTHREE __* ADDTWO __P SSR
ADDTWO __* ADDONE __P SSR
ADDONE __* INIT __P RRR
ADDONE !_* INIT *_* RRR
