HEADS AD

START AA CHECKAA __ RR
START AB CHECKAB __ RR
START A_ CHECKA_ __ RR
START BA CHECKBA __ RR
START BB CHECKBB __ RR
START B_ CHECKB_ __ RR
START __ STOP __ RR

CHECKAA AA CHECKAA @@ RR
CHECKAA AB CHECKAB @_ RR
CHECKAA A_ CHECKA_ @_ RR
CHECKAA _A CHECK_A _@ RR
CHECKAA BA CHECKBA _@ RR
CHECKAA BB CHECKBB __ RR
CHECKAA B_ CHECKB_ __ RR
CHECKAA _B CHECK_B __ RR
CHECKAA __ STOP __ RR

CHECKAB AA CHECKAA @_ RR
CHECKAB AB CHECKAB @@ RR
CHECKAB A_ CHECKA_ @_ RR
CHECKAB _A CHECK_A _@ RR
CHECKAB BA CHECKBA __ RR
CHECKAB BB CHECKBB _@ RR
CHECKAB B_ CHECKB_ __ RR
CHECKAB _B CHECK_B _@ RR
CHECKAB __ STOP __ RR

CHECKBA AA CHECKAA _@ RR
CHECKBA AB CHECKAB __ RR
CHECKBA A_ CHECKA_ __ RR
CHECKBA _A CHECK_A _@ RR
CHECKBA BA CHECKBA @@ RR
CHECKBA BB CHECKBB @_ RR
CHECKBA B_ CHECKB_ @_ RR
CHECKBA _B CHECK_B __ RR
CHECKBA __ STOP __ RR

CHECKBB AA CHECKAA __ RR
CHECKBB AB CHECKAB _@ RR
CHECKBB A_ CHECKA_ __ RR
CHECKBB _A CHECK_A __ RR
CHECKBB BA CHECKBA @_ RR
CHECKBB BB CHECKBB @@ RR
CHECKBB B_ CHECKB_ @_ RR
CHECKBB _B CHECK_B _@ RR
CHECKBB __ STOP __ RR

CHECK_A AA CHECKAA _@ RR
CHECK_A AB CHECKAB __ RR
CHECK_A A_ CHECKA_ __ RR
CHECK_A _A CHECK_A _@ RR
CHECK_A BA CHECKBA _@ RR
CHECK_A BB CHECKBB __ RR
CHECK_A B_ CHECKB_ __ RR
CHECK_A _B CHECK_B __ RR
CHECK_A __ STOP __ RR

CHECKA_ AA CHECKAA @_ RR
CHECKA_ AB CHECKAB @_ RR
CHECKA_ A_ CHECKA_ @_ RR
CHECKA_ _A CHECK_A __ RR
CHECKA_ BA CHECKBA __ RR
CHECKA_ BB CHECKBB __ RR
CHECKA_ B_ CHECKB_ __ RR
CHECKA_ _B CHECK_B __ RR
CHECKA_ __ STOP __ RR

CHECK_B AA CHECKAA __ RR
CHECK_B AB CHECKAB _@ RR
CHECK_B A_ CHECKA_ __ RR
CHECK_B _A CHECK_A __ RR
CHECK_B BA CHECKBA __ RR
CHECK_B BB CHECKBB _@ RR
CHECK_B B_ CHECKB_ __ RR
CHECK_B _B CHECK_B _@ RR
CHECK_B __ STOP __ RR

CHECKB_ AA CHECKAA __ RR
CHECKB_ AB CHECKAB __ RR
CHECKB_ A_ CHECKA_ __ RR
CHECKB_ _A CHECK_A __ RR
CHECKB_ BA CHECKBA @_ RR
CHECKB_ BB CHECKBB @_ RR
CHECKB_ B_ CHECKB_ @_ RR
CHECKB_ _B CHECK_B __ RR
CHECKB_ __ STOP __ RR