HEADS AAAAA

START ***** EXPLORE ***** LUSRD

EXPLORE **AAA EXPLORE @@_** LURRR
EXPLORE **AAB EXPLORE @*_** LURRR
EXPLORE **ABA EXPLORE @*_** LURRR
EXPLORE **ABB EXPLORE **_** LURRR

EXPLORE **BAA EXPLORE **_** LURRR
EXPLORE **BAB EXPLORE @*_** LURRR
EXPLORE **BBA EXPLORE @*_** LURRR
EXPLORE **BBB EXPLORE @@_** LURRR

EXPLORE **A_A BACKTRACK @*_** LUDDD
EXPLORE **A_B BACKTRACK **_** LUDDD
EXPLORE **B_A BACKTRACK **_** LUDDD
EXPLORE **B_B BACKTRACK @*_** LUDDD

BACKTRACK **!** BACKTRACK ***** SSLLL
BACKTRACK **_** EXPLORE ***** SSRRR

EXPLORE **AA_ EXPLORE @*_** LURRR
EXPLORE **AB_ EXPLORE **_** LURRR
EXPLORE **BA_ EXPLORE **_** LURRR
EXPLORE **BB_ EXPLORE @*_** LURRR

EXPLORE **!__ STOP **_** SSSSS
