HEADS AA

START !! LOOP ** SR

LOOP _! LOOP _* RR
LOOP AA LOOP @* RR
LOOP AB LOOP _* RR
LOOP BA LOOP _* RR
LOOP BB LOOP @* RR
LOOP !_ BACKTRACK __ DD
LOOP __ STOP __ SS

BACKTRACK !_ BACKTRACK *_ LL
BACKTRACK AA BACKTRACK *@ LL
BACKTRACK AB BACKTRACK *_ LL
BACKTRACK BA BACKTRACK *_ LL
BACKTRACK BB BACKTRACK *@ LL
BACKTRACK _! LOOP __ DD
BACKTRACK __ STOP __ SS 